### ISSUE TITLE
Runtime error exit code 0x***

### ISSUE THREAD

**Issue by m1gelka** [LimerBoy/StormKitty#1]
runtime error exit code 0xea19....

**Comment by LimerBoy** [comment]
Hi, this is a fake error. Appears when launched in a sandbox or virtual machine.

**Comment by secor1594** [comment]
I can't create a build. no file stub.exe

**Comment by m1gelka** [comment]
> Hi, this is a fake error. Appears when launched in a sandbox or virtual machine.

haaa i run this program on real machine

**Comment by LimerBoy** [comment]
Hmm, i will fix it in next update. You can disable AntiAnalysis in builder.

**Comment by LimerBoy** [comment]
@secor1594 maybe antivirus deleted stub. Try disable it and download builder again.

**Comment by LimerBoy** [comment]
I added some features and bug fixes:
https://github.com/LimerBoy/StormKitty/releases/tag/1.2
