### ISSUE TITLE
System.Net.WebException Error

### ISSUE THREAD

**Issue by weazy420** [LimerBoy/StormKitty#2]
My Token and ChatID is correct, i checked that three times.

ERROR:
System.Net.WebException: The remote server has corrected an error: (400) Invalid rights.
   at System.Net.WebClient.DownloadDataInternal (Uri address, WebRequest & request)
   with System.Net.WebClient.DownloadString (Uri address)
   for System.Net.WebClient.DownloadString (string address)
   for StormKittyBuilder.telegram.SendMessage (String-Text, String-Token, String-Chat-ID) in Desktop \ StormKitty \ builder \ StormKittyBuilder \ Modules \ telegram.cs: line 19.
(!) Connection to Telegram Bot API failed!
    Press any key to exit ...

**Comment by LimerBoy** [comment]
Send the version of your OS
and the Net Framework version you have installed.

**Comment by weazy420** [comment]
> Send the version of your OS
> the Net Framework version you have installed
> and data that you entered in the builder.
