### ISSUE TITLE
How to enable keylogger, clipper, webcam screenshots

### ISSUE THREAD

**Issue by Kiraaaaaaaaaaaaaaaa** [LimerBoy/StormKitty#5]
Как настроить встроенный клиппер, включить снимки с вебкамеры и кейлоггер?

**Comment by LimerBoy** [comment]
> Как настроить встроенный клиппер, включить снимки с вебкамеры и кейлоггер?

В билдере нужно включить автозагрузку. И у вас появятся новые настройки.
